name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    name: Deployment

    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:  ${{ secrets.SSH_KEY }}
          script: |
            whoami
            ls -la
            echo "Environment $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
  
  