name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  ssh:
    name: Deployment via SSH

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Test
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -vvv ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "whoami"


      #     mkdir -p ~/.ssh/
      #     echo "$SSH_KEY" > ~/.ssh/staging.key
      #     chmod 600 ~/.ssh/staging.key
      #     cat >>~/.ssh/config <<END
      #     Host *
      #       LogLevel VERBOSE
      #     Host app
      #       HostName $SSH_HOST
      #       User $SSH_USER
      #       IdentityFile ~/.ssh/staging.key
      #       StrictHostKeyChecking no
      #     END
      #   env:
      #     SSH_USER: ${{ secrets.SSH_USER }}
      #     SSH_KEY: ${{ secrets.SSH_KEY }}
      #     SSH_HOST: ${{ secrets.SSH_HOST }}

      # - name: Try to launch command
      #   run: ssh app 'whoami'

  # deploy:
  #   name: Deployment

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deployment
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key:  ${{ secrets.SSH_KEY }}
  #         debug: true
  #         envs: ENVIRONMENT
  #         script: |
  #           whoami
  #           ls -la
  #           echo "Environment $ENVIRONMENT"
  #       env:
  #         ENVIRONMENT: ${{ inputs.environment }}
  
  