name: Deployment

defaults:
  run:
    shell: bash -ieo pipefail {0}
    
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to update"
        required: true
        default: "staging"
        type: choice
        options:
        - staging
        - production

jobs:
  ftp_file_event:
     name: "File deployment for ${{ inputs.environment }} environment"
     
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout project [unused]
         uses: actions/checkout@v4

       - name: "Create ${{ inputs.environment }} file to source"
         uses: 1arp/create-a-file-action@0.4.5
         with:
           path: "deployment"
           isAbsolutePath: false
           file: ${{ inputs.environment }}
           content: |
             ${{ github.sha }}

       - name: "Send ${{ inputs.environment }} file to server via FTP" 
         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
         with:
           server: ${{ secrets.FTP_HOST }}
           username: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
           local-dir: "deployment/"
           server-dir: "deployment/"
  
  
